# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: manifest.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'manifest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emanifest.proto\x12\x08manifest\"c\n\x1bRawAssetManifestRecordEntry\x12\x12\n\nasset_name\x18\x01 \x01(\t\x12\x14\n\x0cruntime_size\x18\x02 \x01(\x05\x12\x1a\n\x12\x63lone_runtime_size\x18\x03 \x01(\x05\"\xee\x01\n\x16RawAssetManifestRecord\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12\x0c\n\x04size\x18\x03 \x01(\x05\x12\x19\n\x11uncompressed_size\x18\x04 \x01(\x05\x12\x0e\n\x06shared\x18\x05 \x01(\x08\x12\x0c\n\x04rank\x18\x06 \x01(\x05\x12\x13\n\x0bpackageType\x18\x07 \x01(\x05\x12\x36\n\x07\x65ntries\x18\x08 \x03(\x0b\x32%.manifest.RawAssetManifestRecordEntry\x12\x14\n\x0c\x64\x65pendencies\x18\t \x03(\t\x12\x0b\n\x03\x63rc\x18\n \x01(\r\"\xb5\x01\n\x10RawAssetManifest\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x31\n\x07records\x18\x02 \x03(\x0b\x32 .manifest.RawAssetManifestRecord\x12\x10\n\x08platform\x18\x03 \x01(\t\x12\x12\n\ntex_format\x18\x04 \x01(\t\x12\x12\n\nenviorment\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x04\x12\x10\n\x08revision\x18\x07 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manifest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RAWASSETMANIFESTRECORDENTRY']._serialized_start=28
  _globals['_RAWASSETMANIFESTRECORDENTRY']._serialized_end=127
  _globals['_RAWASSETMANIFESTRECORD']._serialized_start=130
  _globals['_RAWASSETMANIFESTRECORD']._serialized_end=368
  _globals['_RAWASSETMANIFEST']._serialized_start=371
  _globals['_RAWASSETMANIFEST']._serialized_end=552
# @@protoc_insertion_point(module_scope)
