import markdown

html_head = """
<!-- this file is generated by make_docs.py -->

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <title>SWGoH AssetAPI</title>
    <style>
        body {
            font-family: sans-serif, arial;
            max-width: 800px;
            margin: 2em auto;
            padding: 0 1em;
            line-height: 1.6;
            background: #f9f9f9;
            color: #333;
        }

        pre {
            background: #2d2d2d;
            color: #f8f8f2;
            padding: 1em;
            overflow-x: auto;
            border-radius: 5px;
        }

        code {
            background: #eee;
            padding: 2px 4px;
            border-radius: 4px;
            font-family: Consolas, monospace;
        }

        pre code {
            background: none;
            padding: 0;
            color: inherit;
        }

        h1,
        h2,
        h3 {
            color: #222;
        }

        a {
            color: #0066cc;
        }
    </style>
</head>

<body>"""

html_foot = """
</body>

</html>
"""

with open("README.md", 'r') as file:
    readme = file.read()
    
html = html_head
html += markdown.markdown(readme, extensions=["fenced_code", "tables", "codehilite", "toc"])
html += html_foot

with open('README.html', 'w') as file:
    file.write(html)